server:
  port: 8083
  servlet:
    jsp:
      init-parameters:
        development: true


mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  config-location: classpath:mybatis/mybatis-config.xml

springdoc:
  api-docs.path: /api-docs
  swagger-ui.path: /swagger-ui-custom.html
  swagger-ui.operationsSorter: method

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

# 모니터링
management:
  endpoints:
    web:
      exposure:
        include: "*"  # 모든 엔드포인트 노출
  endpoint:
    prometheus:
      enabled: true  # Prometheus 엔드포인트 활성화